In [ ]:
import numpy as np
import pandas as pd

In [ ]:
char_dict = {
    ' ':0,   
    'a':1,
    'b':2,
    'c':3,
    'd':4,
    'e':5,
    'f':6,
    'g':7,
    'h':8,
    'i':9,
    'j':10,
    'k':11,
    'l':12,
    'm':13,
    'n':14,
    'o':15,
    'p':16,
    'q':17,
    'r':18,
    's':19,
    't':20,
    'u':21,
    'v':22,
    'w':23,
    'x':24,
    'y':25,
    'z':26,
    'á':27,
    'é':28,
    'í':29,
    'ó':30,
    'ú':31,
    'ñ':32,
    'ü':33,
    'ä':34,
    'å':35,
    'ö':36,
    'ß':37,
}

size = len(char_dict)
size

38

In [ ]:
def updateT(word, char, T):
    
    if char in word:
        
        row = char_dict[char]
        indice = [i for i, letter in enumerate(word) if letter == char]
        count = len(indice)
        #print('count=%s'%count)
        T[row][-1] += count
        col=None
        
        next_indice = [i+1 for i in indice]
        #print('next_indice=%s'%next_indice)
        
        for i in next_indice:
            
            if i == len(word):
                T[row][0] += 1
            else:
                next_char = word[i]
                #print('next_char=%s'%next_char)
                col = char_dict[next_char]
                #print(row)
                #print('updated col=%s'%col)
                T[row][col] += 1
    
    else:
        None
    

In [ ]:
def computeT(df, T):
    rows, columns = df.shape[0], df.shape[1]
    for char in char_dict:
        #print('char=%s'%char)
        for r in range(rows):
            #print('r = %s'%r)
            word = df.iloc[r][0]
            updateT(word, char, T)

## English

In [ ]:
df_E = pd.read_csv("1000 most common words - English.csv", header=None)

# Data cleaning
df_E = df_E.replace(to_replace="don't",value='dont')
df_E.iloc[241,0] = 'dont'
df_E.iloc[751,0] = 'wont'

T_E = np.zeros((size,size+1))

computeT(df_E, T_E)

In [ ]:
T_E_counts = T_E

In [ ]:
T_E_counts

array([[  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  4.,   0.,   7., ...,   0.,   0., 370.],
       [  4.,  11.,   0., ...,   0.,   0.,  87.],
       ...,
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.]])

In [ ]:
df_TE_C = pd.DataFrame(T_E_counts[:,:-1], index=char_dict, columns = char_dict, dtype=int)
df_TE_C.head()

a  b   c   d   e  f   g   h   i  ...  é  í  ó  ú  ñ  ü  ä  å  ö  ß
    0   0  0   0   0   0  0   0   0   0  ...  0  0  0  0  0  0  0  0  0  0
a   4   0  7  19  19   0  3  11   0  25  ...  0  0  0  0  0  0  0  0  0  0
b   4  11  0   0   0  19  0   0   0   3  ...  0  0  0  0  0  0  0  0  0  0
c   3  18  0   2   0  32  0   0  32   9  ...  0  0  0  0  0  0  0  0  0  0
d  87   5  0   0   3  34  0   1   0  14  ...  0  0  0  0  0  0  0  0  0  0

[5 rows x 38 columns]

In [ ]:
total = T_E[:,-1]
for i in range(T_E.shape[0]):
    if total[i] != 0:
        T_E[i] = T_E[i] / total[i]
T_E = T_E[:,:-1]

In [ ]:
T_E

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.01081081, 0.        , 0.01891892, ..., 0.        , 0.        ,
        0.        ],
       [0.04597701, 0.12643678, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
df_TE = pd.DataFrame(T_E, index=char_dict, columns = char_dict)
df_TE.head()

a         b         c         d         e         f  \
   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
a  0.010811  0.000000  0.018919  0.051351  0.051351  0.000000  0.008108   
b  0.045977  0.126437  0.000000  0.000000  0.000000  0.218391  0.000000   
c  0.015228  0.091371  0.000000  0.010152  0.000000  0.162437  0.000000   
d  0.497143  0.028571  0.000000  0.000000  0.017143  0.194286  0.000000   

          g         h         i  ...    é    í    ó    ú    ñ    ü    ä    å  \
   0.000000  0.000000  0.000000  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
a  0.029730  0.000000  0.067568  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
b  0.000000  0.000000  0.034483  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
c  0.000000  0.162437  0.045685  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
d  0.005714  0.000000  0.080000  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

     ö    ß  
   0.0  0.0  
a  0.0  0.0  
b  0.0  0.0  
c  0.0  0.0  
d  0.0  0.0  

[5 rows x 38 columns]

## Spanish

In [ ]:
df_Sp = pd.read_csv("1000 most common words - Spanish.csv", header=None)

# Data cleaning
df_Sp = df_Sp[[0]]
df_Sp = df_Sp.replace(to_replace='por tanto,', value='por tanto')
df_Sp = df_Sp.replace(to_replace='particular,', value='particular')
df_Sp = df_Sp.replace(to_replace='a su vez,', value='a su vez')

T_Sp = np.zeros((size,size+1))

computeT(df_Sp,T_Sp)

In [ ]:
T_Sp_counts = T_Sp

In [ ]:
T_Sp_counts

array([[  0.,   1.,   1., ...,   0.,   0.,  34.],
       [230.,   0.,  19., ...,   0.,   0., 760.],
       [  0.,  21.,   0., ...,   0.,   0.,  95.],
       ...,
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.]])

In [ ]:
df_TSp_C = pd.DataFrame(T_Sp_counts[:,:-1], index=char_dict, columns = char_dict, dtype=int)
df_TSp_C.head()

a   b   c   d   e  f  g   h   i  ...  é  í  ó  ú  ñ  ü  ä  å  ö  ß
     0   1   1   3   6   4  2  1   3   1  ...  0  0  0  0  0  0  0  0  0  0
a  230   0  19  27  54   3  1  8   2   1  ...  0  4  0  1  6  0  0  0  0  0
b    0  21   0   0   0  10  0  0   0  14  ...  1  1  0  1  0  0  0  0  0  0
c    0  70   0   4   0  26  0  0  22  59  ...  1  1  2  0  0  0  0  0  0  0
d   13  44   0   0   0  66  0  0   0  32  ...  0  5  2  0  0  0  0  0  0  0

[5 rows x 38 columns]

In [ ]:
total = T_Sp[:,-1]
for i in range(T_Sp.shape[0]):
    if total[i] != 0:
        T_Sp[i] = T_Sp[i] / total[i]
T_Sp = T_Sp[:,:-1]

In [ ]:
T_Sp

array([[0.        , 0.02941176, 0.02941176, ..., 0.        , 0.        ,
        0.        ],
       [0.30263158, 0.        , 0.025     , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.22105263, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
df_TSp = pd.DataFrame(T_Sp, index=char_dict, columns = char_dict)
df_TSp.head()

a         b         c         d         e         f  \
   0.000000  0.029412  0.029412  0.088235  0.176471  0.117647  0.058824   
a  0.302632  0.000000  0.025000  0.035526  0.071053  0.003947  0.001316   
b  0.000000  0.221053  0.000000  0.000000  0.000000  0.105263  0.000000   
c  0.000000  0.225806  0.000000  0.012903  0.000000  0.083871  0.000000   
d  0.055319  0.187234  0.000000  0.000000  0.000000  0.280851  0.000000   

          g         h         i  ...         é         í         ó         ú  \
   0.029412  0.088235  0.029412  ...  0.000000  0.000000  0.000000  0.000000   
a  0.010526  0.002632  0.001316  ...  0.000000  0.005263  0.000000  0.001316   
b  0.000000  0.000000  0.147368  ...  0.010526  0.010526  0.000000  0.010526   
c  0.000000  0.070968  0.190323  ...  0.003226  0.003226  0.006452  0.000000   
d  0.000000  0.000000  0.136170  ...  0.000000  0.021277  0.008511  0.000000   

          ñ    ü    ä    å    ö    ß  
   0.000000  0.0  0.0  0.0  0.0  0.0  
a  0.007895  0.0  0.0  0.0  0.0  0.0  
b  0.000000  0.0  0.0  0.0  0.0  0.0  
c  0.000000  0.0  0.0  0.0  0.0  0.0  
d  0.000000  0.0  0.0  0.0  0.0  0.0  

[5 rows x 38 columns]

## German

In [ ]:
df_G = pd.read_csv("1000 most common words - German.csv", header=None)

# Data cleaning
df_G = df_G[[0]]
df_G.iloc[95, 0] = 'in der nähe von'
df_G.iloc[241, 0] = 'unterlassen sie'
df_G = df_G.replace(to_replace='Haupt-', value='Haupt')

T_G = np.zeros((size,size+1))

computeT(df_G,T_G)

In [ ]:
T_G_counts = T_G

In [ ]:
T_G_counts

array([[  0.,   0.,   0., ...,   0.,   0.,   9.],
       [  6.,   2.,   9., ...,   0.,   4., 311.],
       [  5.,   5.,   1., ...,   0.,   0., 123.],
       ...,
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   1.,  19.],
       [  9.,   0.,   0., ...,   0.,   0.,  17.]])

In [ ]:
df_TG_C = pd.DataFrame(T_G_counts[:,:-1], index=char_dict, columns = char_dict, dtype=int)
df_TG_C.head()

a  b   c  d   e  f   g    h   i  ...  é  í  ó  ú  ñ  ü  ä  å  ö  ß
    0  0  0   0  1   0  0   0    0   0  ...  0  0  0  0  0  0  0  0  0  0
a   6  2  9  22  7   0  6  20   14   2  ...  0  0  0  0  0  0  0  0  0  4
b   5  5  1   0  1  71  0   0    1   7  ...  0  0  0  0  0  0  0  0  0  0
c   0  0  0   0  0   1  0   0  164   0  ...  0  0  0  0  0  0  0  0  0  0
d  43  6  0   1  0  61  0   0    0  15  ...  0  0  0  0  0  1  0  0  0  0

[5 rows x 38 columns]

In [ ]:
total = T_G[:,-1]
for i in range(T_G.shape[0]):
    if total[i] != 0:
        T_G[i] = T_G[i] / total[i]
T_G = T_G[:,:-1]

In [ ]:
T_G

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.0192926 , 0.00643087, 0.02893891, ..., 0.        , 0.        ,
        0.01286174],
       [0.04065041, 0.04065041, 0.00813008, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.05263158],
       [0.52941176, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
df_TG = pd.DataFrame(T_G, index=char_dict, columns = char_dict)
df_TG.head()

a         b         c         d         e         f  \
   0.000000  0.000000  0.000000  0.000000  0.111111  0.000000  0.000000   
a  0.019293  0.006431  0.028939  0.070740  0.022508  0.000000  0.019293   
b  0.040650  0.040650  0.008130  0.000000  0.008130  0.577236  0.000000   
c  0.000000  0.000000  0.000000  0.000000  0.000000  0.005376  0.000000   
d  0.298611  0.041667  0.000000  0.006944  0.000000  0.423611  0.000000   

          g         h         i  ...    é    í    ó    ú    ñ         ü    ä  \
   0.000000  0.000000  0.000000  ...  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
a  0.064309  0.045016  0.006431  ...  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
b  0.000000  0.008130  0.056911  ...  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
c  0.000000  0.881720  0.000000  ...  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
d  0.000000  0.000000  0.104167  ...  0.0  0.0  0.0  0.0  0.0  0.006944  0.0   

     å    ö         ß  
   0.0  0.0  0.000000  
a  0.0  0.0  0.012862  
b  0.0  0.0  0.000000  
c  0.0  0.0  0.000000  
d  0.0  0.0  0.000000  

[5 rows x 38 columns]

## Swedish

In [ ]:
df_Sw = pd.read_csv("1000 most common words - Swedish.csv", header=None)
df_Sw = df_Sw[[0]]

T_Sw = np.zeros((size,size+1))

computeT(df_Sw, T_Sw)

In [ ]:
T_Sw_counts = T_Sw
T_Sw_counts

array([[  0.,   0.,   0., ...,   0.,   0.,   4.],
       [203.,   0.,   2., ...,   0.,   0., 506.],
       [  3.,  13.,   3., ...,   3.,   0.,  99.],
       ...,
       [ 14.,   0.,   0., ...,   0.,   0.,  79.],
       [  5.,   0.,   0., ...,   0.,   0.,  94.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.]])

In [ ]:
df_TSw_C = pd.DataFrame(T_Sw_counts[:,:-1], index=char_dict, columns = char_dict, dtype=int)
df_TSw_C.head()

a  b  c   d   e  f   g  h   i  ...  é  í  ó  ú  ñ  ü  ä  å  ö  ß
     0   0  0  0   0   0  0   1  0   1  ...  0  0  0  0  0  0  0  0  0  0
a  203   0  2  4  16   0  3  17  2   0  ...  0  0  0  0  0  0  0  0  0  0
b    3  13  3  0   0  22  0   0  0   6  ...  0  0  0  0  0  0  5  2  3  0
c    0   2  0  0   0   8  0   0  4   5  ...  0  0  0  0  0  0  0  0  0  0
d   66  30  1  0   8  59  0   1  0  16  ...  1  0  0  0  0  0  3  2  5  0

[5 rows x 38 columns]

In [ ]:
total = T_Sw[:,-1]
for i in range(T_Sw.shape[0]):
    if total[i] != 0:
        T_Sw[i] = T_Sw[i] / total[i]
T_Sw = T_Sw[:,:-1]

In [ ]:
df_TSw = pd.DataFrame(T_Sw, index=char_dict, columns = char_dict)
df_TSw.head()

a         b         c         d         e         f  \
   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
a  0.401186  0.000000  0.003953  0.007905  0.031621  0.000000  0.005929   
b  0.030303  0.131313  0.030303  0.000000  0.000000  0.222222  0.000000   
c  0.000000  0.033898  0.000000  0.000000  0.000000  0.135593  0.000000   
d  0.297297  0.135135  0.004505  0.000000  0.036036  0.265766  0.000000   

          g         h         i  ...         é    í    ó    ú    ñ    ü  \
   0.250000  0.000000  0.250000  ...  0.000000  0.0  0.0  0.0  0.0  0.0   
a  0.033597  0.003953  0.000000  ...  0.000000  0.0  0.0  0.0  0.0  0.0   
b  0.000000  0.000000  0.060606  ...  0.000000  0.0  0.0  0.0  0.0  0.0   
c  0.000000  0.067797  0.084746  ...  0.000000  0.0  0.0  0.0  0.0  0.0   
d  0.004505  0.000000  0.072072  ...  0.004505  0.0  0.0  0.0  0.0  0.0   

          ä         å         ö    ß  
   0.000000  0.000000  0.000000  0.0  
a  0.000000  0.000000  0.000000  0.0  
b  0.050505  0.020202  0.030303  0.0  
c  0.000000  0.000000  0.000000  0.0  
d  0.013514  0.009009  0.022523  0.0  

[5 rows x 38 columns]